//! rust-protobuf bindings generated by `build.rs` from `proto/` (packages
//! `versioned_document`, `topotext`, `CRDT` → modules `versioned_document`,
//! `topotext`, `crdt`). Unknown fields are kept in each message's
//! `special_fields`, which is what makes byte-exact round trips possible.
//!
//! Two behaviours differ from protobuf-es, which icloud-md uses: rust-protobuf
//! refuses to parse a message missing a `required` field
//! (`parse_from_bytes` checks initialization; use `merge_from` +
//! skipping the check where icloud-md tolerates it), and it rejects invalid
//! UTF-8 in `string` fields where protobuf-es substitutes U+FFFD.

include!(concat!(env!("OUT_DIR"), "/proto/mod.rs"));
